### ISSUE TITLE
Unable to fetch latest episodes on BatchFetchPodcasts call

### ISSUE THREAD

**Issue by zzzux** [ListenNotes/podcast-api-go#6]
Hello!
There is a problem with method for batch fetch podcasts with latests episodes.

Expected due to docs https://www.listennotes.com/api/docs/?lang=go#post-api-v2-podcasts

```go
func main() {
  client := listennotes.NewClient("<SIGN UP FOR API KEY>")
  resp, err := client.BatchFetchPodcasts(map[string]string{
    "ids": "3302bc71139541baa46ecb27dbf6071a",
    "show_latest_episodes": "1",
    "next_episode_pub_date": "1557394247000",
  });
  if err == nil {
    // Print out the entire response data as a string
    fmt.Println(resp.ToJSON())
```

Actual method interface:
```go
func (c *standardHTTPClient) BatchFetchPodcasts(ids []string, args map[string]string) (*Response, error) {
	return c.post("podcasts", args, url.Values{
		"ids": []string{strings.Join(ids, ",")},
	})
}
```

So, i cant pass additional body parameters.

**Comment by wenbinf** [comment]
@zzzux Do you use a real API key? Or do you sending requests to API mock servers for testing?

**Comment by zzzux** [comment]
@wenbinf real API key

**Comment by wenbinf** [comment]
> @wenbinf real API key

Thanks for your reply. Looks like it's a bug on our end. Looking now.

Using curl or SDKs of other non-go languages is working.

**Comment by wenbinf** [comment]
@zzzux It should be fixed now. Please try again.

**Comment by zzzux** [comment]
@wenbinf Thank you for quick reply! Working fine now.
